### ISSUE TITLE
Non-ASCII character '\xed' in file 오류

### ISSUE THREAD

**Issue by jeongwookie** [lovit/sejong_corpus_cleaner#19]
안녕하세요. 사용중 질문 하나 드리려 합니다.
python build_corpus.py  --corpus_type sejong 실행 시 다음과 같은 오류가 발생합니다.

Traceback (most recent call last):
  File "build_corpus.py", line 5, in <module>
    from sejong_corpus_cleaner import get_data_paths
  File "../sejong_corpus_cleaner/__init__.py", line 4, in <module>
    from .loader import Sentence
  File "../sejong_corpus_cleaner/loader.py", line 25
SyntaxError: Non-ASCII character '\xed' in file ../sejong_corpus_cleaner/loader.py on line 26, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

인코딩 문제인 것 같은데, 한번 검토해 주시면 감사합니다.

**Comment by lovit** [comment]
해당 문제는 python2 로 스크립트를 실행할 때 발생하는 문제로 생각됩니다. 저도 방금 python2 로 실행시키니 동일한 문제가 발생하였습니다. Python 3 으로 실행시키면 잘 작동함을 다시 확인하였습니다.

**Comment by jeongwookie** [comment]
답변 감사합니다. 혹시 다른 질문을 드려도 괜찮을까요?
세종 말뭉치 다운로드에 관한 건인데, https://github.com/coolengineer/sejong-corpus 을 사용하여 데이터를 받았습니다. 작성하신 스크립트로 정제를 진행하고 싶을 때, UTF-16 (원본) 을 그대로 사용하여도 되나요?

Traceback (most recent call last):
  File "../sejong_corpus_cleaner/loader.py", line 432, in read_txt_as_soup
    text = f.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python3.5/encodings/utf_16.py", line 67, in _buffer_decode
    raise UnicodeError("UTF-16 stream does not start with BOM")
UnicodeError: UTF-16 stream does not start with BOM

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_corpus.py", line 51, in <module>
    main()
  File "build_corpus.py", line 42, in main
    write_sentences(sents, path)
  File "../sejong_corpus_cleaner/maker.py", line 98, in write_sentences
    for i, sent in enumerate(sentences):
  File "../sejong_corpus_cleaner/loader.py", line 184, in __iter__
    remain_dummy_morpheme=False, num_sents=self.num_sents)
  File "../sejong_corpus_cleaner/loader.py", line 349, in load_a_sejong_file
    soup = read_txt_as_soup(path)
  File "../sejong_corpus_cleaner/loader.py", line 436, in read_txt_as_soup
    raise ValueError('Failed to read txt: {}'.format(path))
ValueError: Failed to read txt: ../data/raw/written/BA90A067.txt

**Comment by lovit** [comment]
해당 파일을 확인해보니 utf-16 bom 이네요. 떠올려보니 배포되는 파일에 인코딩이 두 종류이상이었던게 기억나네요. 해당 인코뎅은 `utf-16le` 로 여시면 됩니다.

**Comment by jeongwookie** [comment]
답변 감사합니다! 해당 파일을 저도 확인했습니다. 그러면 각 파일들의 인코딩을 확인해서 각각 다르게 읽어야 하는 건가요? 작성해 놓으신 build_corpus.py 스크립트 파일을 파일 인코딩에 맞게 케이스를 나누어 수정해야 될 것으로 이해가 됩니다. 혹시 당시에 본 스크립트를 작성하실 때 파일 인코딩을 통일하신 방법이 있다면 어떻게 하셨는지 궁금합니다.

**Comment by lovit** [comment]
우분투를 사용하신다면 이처럼 한 파일의 인코딩을 변경할 수 있습니다.

```
iconv -f utf-16 -t utf-8 BTJO0444.txt --output BTJO0444_utf8.txt
```

파일의 인코딩을 확인할 때에는 다음의 명령어를 이용할 수 있습니다.

```
file BTJO0444.txt
```

```
BTJO0444.txt: HTML document, Little-endian UTF-16 Unicode text, with CRLF line terminators 
```

저도 쉘 스크립팅에 능숙한 편이 아니어서 왠지 기억에 파이썬에서 process 를 실행시키며 그 결과를 보고 `-f` 의 값에 넣는 원파일의 인코딩을 지정했었던 것 같습니다. 파이썬에서 process 를 실행시키는 방법은 아래의 블로그를 링크로 뒀습니다.

http://noplanlife.com/?p=949
